//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicAid01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patientapp
    {
        public int patientId { get; set; }
        public string patientName { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string Doctortype { get; set; }
    }
}
