//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicAid01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENTINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PATIENTINFO()
        {
            this.Medicines = new HashSet<Medicine>();
        }
    
        public int PatientInfoId { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientLastName { get; set; }
        public int Age { get; set; }
        public double Weight { get; set; }
        public string Gender { get; set; }
        public string MedicalHistory { get; set; }
        public string BloodGrp { get; set; }
        public int PatientId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine> Medicines { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
